### ISSUE TITLE
'show logfile' broke in TestShell

### ISSUE THREAD

**Issue by packetpunter** [packetpunter/pyNetTestShell#5]
```python

net_test> show logfile
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/blue/homebrew/lib/python3.11/site-packages/TestShell/__main__.py", line 7, in <module>
    main()
  File "/Users/blue/homebrew/lib/python3.11/site-packages/TestShell/__main__.py", line 4, in main
    shellCmdInteractive().cmdloop()
  File "/Users/blue/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
           ^^^^^^^^^^^^^^^^^
  File "/Users/blue/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/cmd.py", line 217, in onecmd
    return func(arg)
           ^^^^^^^^^
  File "/Users/blue/homebrew/lib/python3.11/site-packages/TestShell/shellCmd.py", line 94, in do_show
    self.do_get(user_input)
  File "/Users/blue/homebrew/lib/python3.11/site-packages/TestShell/shellCmd.py", line 104, in do_get
    self._userprint(self._LOGFILE)
                    ^^^^^^^^^^^^^
AttributeError: 'shellCmdInteractive' object has no attribute '_LOGFILE'
```

**Comment by packetpunter** [comment]
fixed in 2.2.1
